site_name: GalaxyKickStart
pages:
 - Home: index.md
 - What is GalaxyKickStart: about.md
 - Getting started: getting_started.md
 - customizations.md
 - installing tools and workflows.md
 - Examples:
   - examples/docker.md
   - examples/vagrant.md
 - Frequently asked questions: faq.md
 - Available roles: available_roles.md
 - Available variables: available_variables.md
 - GalaxyKickStart Use Cases: 
   - metavisitor.md
   - GKS2slurm.md
   - GKSfromWorflows.md
theme: readthedocs
