galaxy_persistent_directory: /export
galaxy_persist_directories: 
  - { path: "{{ tool_dependency_dir }}", owner: "{{ galaxy_user_name }}" }
  - { path: "{{ shed_tools_dir }}", owner: "{{ galaxy_user_name }}" }
  - { path: "{{ tool_data_dir }}", owner: "{{ galaxy_user_name }}" }
  - { path: "{{ galaxy_config_dir }}", owner: "{{ galaxy_user_name }}" }
  - { path: "{{ galaxy_config_dir }}/../lib", owner: "{{ galaxy_user_name }}" }
  - { path: "{{ galaxy_mutable_data_dir }}", owner: "{{ galaxy_user_name }}" }
  - { path: "{{ supervisor_postgres_database_path }}", owner: "postgres" }
start_stop_items:
  - "galaxy:"
  - "proftpd"
  - "postgresql"
