- name: Install nfs packages
  apt: pkg={{ item }} state='present'
  with_items:
    - nfs-kernel-server
    - nfs-common

- name: Create nfs_export directory
  file: path={{ nfs_export_galaxy_dir }} state=directory mode=0755 recurse=yes

- name: bind mount persitent directories in nfs_export/galaxy directory
  mount: opts=bind fstype=none state=mounted name={{ item.dest }} src={{ item.src }}
  with_items:
    - { src: "/home/galaxy", dest: "{{ nfs_export_galaxy_dir }}" }
    - { src: "{{ galaxy_persistent_directory }}/home/galaxy/tool_dependencies", dest: "{{ nfs_export_galaxy_dir }}/tool_dependencies" }
    - { src: "{{ galaxy_persistent_directory }}/home/galaxy/shed_tools", dest: "{{ nfs_export_galaxy_dir }}/shed_tools" }
    - { src: "{{ galaxy_persistent_directory }}/home/galaxy/galaxy/tool-data", dest: "{{ nfs_export_galaxy_dir }}/galaxy/tool-data" }
    - { src: "{{ galaxy_persistent_directory }}/home/galaxy/galaxy/config", dest: "{{ nfs_export_galaxy_dir }}/galaxy/config" }
    - { src: "{{ galaxy_persistent_directory }}/home/galaxy/galaxy/database", dest: "{{ nfs_export_galaxy_dir }}/galaxy/database" }

- name: export galaxy data for nfs sharing with slurm slave nodes
  template: src=exports dest=/etc/exports
#  notify:
#    - restart nfs-kernel-server

- name: restart nfs-kernel-server
  service: name=nfs-kernel-server state=restarted
