- name: update proxy prefix in uwsgi section of galaxy.yml
  replace:
    dest: '{{ galaxy_config_dir }}/galaxy.yml'
    regexp: '( *).+galaxy.webapps.galaxy.buildapp:uwsgi_app().*'
    replace: '\1mount{{ ":" }} {{ nginx_galaxy_location }}=galaxy.webapps.galaxy.buildapp:uwsgi_app()\n\1manage-script-name{{ ":" }} true'
    backup: yes
  # eq. to when nginx_galaxy_location != "" see https://github.com/ansible/ansible-lint/issues/457#issuecomment-455038475
  when: nginx_galaxy_location | length

- name: update proxy prefix in uwsgi section of galaxy.yml
  replace:
    dest: '{{ galaxy_config_dir }}/galaxy.yml'
    regexp: '( *).+galaxy.webapps.galaxy.buildapp:uwsgi_app().*?(\n.+manage-script-name.+)'
    replace: '\1module{{ ":" }} galaxy.webapps.galaxy.buildapp:uwsgi_app()'
    backup: yes
  when: not nginx_galaxy_location

# - name: update nginx prefix in galaxy section of galaxy.yml
#   replace:
#     dest: '{{ galaxy_config_dir }}/galaxy.yml'
#     regexp: '( +)prefix{{ ":" }}.+'
#     replace: '\1prefix{{ ":" }} "{{ nginx_galaxy_location }}"'
#     backup: yes

- name: update ftp_upload_site IP address in galaxy.yml
  replace:
    dest: '{{ galaxy_config_dir }}/galaxy.yml'
    regexp: '(.*)ftp_upload_site? {{ ":" }}.+'
    replace: '\1ftp_upload_site{{ ":" }} "ftp://{{ ipify_public_ip }}"'
    backup: yes

- name: Restart supervisor tasks after prefix and ftp ip are updated in config file
  supervisorctl: name="{{ item }}" state=restarted
  with_items: "{{ start_stop_items }}"
  # eq. to when nginx_galaxy_location != "" see https://github.com/ansible/ansible-lint/issues/457#issuecomment-455038475
  when: nginx_galaxy_location | length
  tags: skip_supervisor_start_in_docker
